# node group for NVD
apiVersion: v1
items:
- apiVersion: aaa.eda.nokia.com/v1alpha1
  kind: NodeGroup
  metadata:
    name: sudo
    namespace: dc1-backend
  spec:
    services:
    - GNMI
    - CLI
    - NETCONF
    - GNOI
    - GNSI
    superuser: true
kind: List
