apiVersion: core.eda.nokia.com/v1
kind: IPAllocationPool
metadata:
  name: systemipv4-pool
  namespace: dc1-backend
spec:
  segments:
  - subnet: 192.0.2.0/24
---
apiVersion: core.eda.nokia.com/v1
kind: IPAllocationPool
metadata:
  name: systemipv4-pool
  namespace: dc1-frontend
spec:
  segments:
  - subnet: 192.0.2.0/24