# © 2025 Nokia  
# Licensed under the BSD 3-Clause License  
# SPDX-License-Identifier: BSD-3-Clause  

apiVersion: config.eda.nokia.com/v1alpha1
kind: Configlet
metadata:
  name: leaf4-leaf5-lag1
  namespace: eda
spec:
  endpoints:
    - leaf4
    - leaf5
  operatingSystem: srl
  priority: 100
  configs:
    - path: .system.network-instance.protocols.evpn.ethernet-segments.bgp-instance{.id==1}.ethernet-segment{.name=="leaf4-leaf5-lag1"}.df-election.timers
      operation: Update
      config: |-
        {
          "activation-timer": 0
        }
---
apiVersion: config.eda.nokia.com/v1alpha1
kind: Configlet
metadata:
  name: leaf5-leaf6-lag3
  namespace: eda
spec:
  endpoints:
    - leaf5
    - leaf6
  operatingSystem: srl
  priority: 100
  configs:
    - path: .system.network-instance.protocols.evpn.ethernet-segments.bgp-instance{.id==1}.ethernet-segment{.name=="leaf5-leaf6-lag3"}.df-election.timers
      operation: Update
      config: |-
        {
          "activation-timer": 0
        }
---
apiVersion: config.eda.nokia.com/v1alpha1
kind: Configlet
metadata:
  name: leaf2-leaf3-leaf4-leaf5-lag2
  namespace: eda
spec:
  endpoints:
    - leaf2
    - leaf3
    - leaf4
    - leaf5
  operatingSystem: srl
  priority: 100
  configs:
    - path: .system.network-instance.protocols.evpn.ethernet-segments.bgp-instance{.id==1}.ethernet-segment{.name=="leaf2-leaf3-leaf4-leaf5-lag2"}.df-election.timers
      operation: Update
      config: |-
        {
          "activation-timer": 0
        }