# © 2025 Nokia  
# Licensed under the BSD 3-Clause License  
# SPDX-License-Identifier: BSD-3-Clause  

# Routed interface to server s5
apiVersion: services.eda.nokia.com/v1alpha1
kind: RoutedInterface
metadata:
  name: leaf1-s5
  namespace: eda
spec:
  arpTimeout: 14400
  interface: leaf1-ethernet-1-4
  ipMTU: 1500
  ipv4Addresses:
    - ipPrefix: 172.16.100.0/31
      primary: true
  router: vrf1
  vlanID: "null"
