# © 2025 Nokia  
# Licensed under the BSD 3-Clause License  
# SPDX-License-Identifier: BSD-3-Clause  

# bridge domains
# if needed, export/import RTs can be manually defined using exportTarget and importTarget options
# EDA makes life easier by just generating it for you
apiVersion: services.eda.nokia.com/v1alpha1
kind: BridgeDomain
metadata:
  name: macvrf-v10
  namespace: eda
spec:
  type: EVPNVXLAN
  vni: 10010
  evi: 10
  tunnelIndexPool: tunnel-index-pool
  macAging: 300
  macDuplicationDetection:
    enabled: true
    holdDownTime: 9
    monitoringWindow: 3
    action: StopLearning
    numMoves: 5
---
apiVersion: services.eda.nokia.com/v1alpha1
kind: BridgeDomain
metadata:
  name: macvrf-v20
  namespace: eda
spec:
  type: EVPNVXLAN
  vni: 10020
  evi: 20
  tunnelIndexPool: tunnel-index-pool
  macAging: 300
  macDuplicationDetection:
    enabled: true
    holdDownTime: 9
    monitoringWindow: 3
    action: StopLearning
    numMoves: 5
---
apiVersion: services.eda.nokia.com/v1alpha1
kind: BridgeDomain
metadata:
  name: macvrf-v30
  namespace: eda
spec:
  type: EVPNVXLAN
  vni: 10030
  evi: 30
  tunnelIndexPool: tunnel-index-pool
  macAging: 300
  macDuplicationDetection:
    enabled: true
    holdDownTime: 9
    monitoringWindow: 3
    action: StopLearning
    numMoves: 5
---
apiVersion: services.eda.nokia.com/v1alpha1
kind: BridgeDomain
metadata:
  name: macvrf-v40
  namespace: eda
spec:
  type: EVPNVXLAN
  vni: 10040
  evi: 40
  tunnelIndexPool: tunnel-index-pool
  macAging: 300
  macDuplicationDetection:
    enabled: true
    holdDownTime: 9
    monitoringWindow: 3
    action: StopLearning
    numMoves: 5
---
apiVersion: services.eda.nokia.com/v1alpha1
kind: BridgeDomain
metadata:
  name: macvrf-v50
  namespace: eda
spec:
  type: EVPNVXLAN
  vni: 10050
  evi: 50
  tunnelIndexPool: tunnel-index-pool
  macAging: 300
  macDuplicationDetection:
    enabled: true
    holdDownTime: 9
    monitoringWindow: 3
    action: StopLearning
    numMoves: 5
---
apiVersion: services.eda.nokia.com/v1alpha1
kind: BridgeDomain
metadata:
  name: macvrf-v60
  namespace: eda
spec:
  type: EVPNVXLAN
  vni: 10060
  evi: 60
  tunnelIndexPool: tunnel-index-pool
  macAging: 300
  macDuplicationDetection:
    enabled: true
    holdDownTime: 9
    monitoringWindow: 3
    action: StopLearning
    numMoves: 5
---
# IRB interfaces
apiVersion: services.eda.nokia.com/v1alpha1
kind: IRBInterface
metadata:
  name: irb-v10
  namespace: eda
spec:
  bridgeDomain: macvrf-v10
  router: vrf1
  ipMTU: 1500
  ipAddresses:
    - ipv4Address:
        ipPrefix: 172.16.10.254/24
        primary: true
  arpTimeout: 14400
  evpnRouteAdvertisementType:
    arpDynamic: true
  hostRoutePopulate:
    dynamic: false
    evpn: false
    static: false
  l3ProxyARPND:
    proxyARP: true
    proxyND: false
---
apiVersion: services.eda.nokia.com/v1alpha1
kind: IRBInterface
metadata:
  name: irb-v20
  namespace: eda
spec:
  bridgeDomain: macvrf-v20
  router: vrf1
  ipMTU: 1500
  ipAddresses:
    - ipv4Address:
        ipPrefix: 172.16.20.254/24
        primary: true
  arpTimeout: 14400
  evpnRouteAdvertisementType:
    arpDynamic: true
  hostRoutePopulate:
    dynamic: false
    evpn: false
    static: false
  l3ProxyARPND:
    proxyARP: true
    proxyND: false
---
apiVersion: services.eda.nokia.com/v1alpha1
kind: IRBInterface
metadata:
  name: irb-v30
  namespace: eda
spec:
  bridgeDomain: macvrf-v30
  router: vrf1
  ipMTU: 1500
  ipAddresses:
    - ipv4Address:
        ipPrefix: 172.16.30.254/24
        primary: true
  arpTimeout: 14400
  evpnRouteAdvertisementType:
    arpDynamic: true
  hostRoutePopulate:
    dynamic: false
    evpn: false
    static: false
  l3ProxyARPND:
    proxyARP: true
    proxyND: false
---
apiVersion: services.eda.nokia.com/v1alpha1
kind: IRBInterface
metadata:
  name: irb-v40
  namespace: eda
spec:
  bridgeDomain: macvrf-v40
  router: vrf2
  ipMTU: 1500
  ipAddresses:
    - ipv4Address:
        ipPrefix: 172.16.40.254/24
        primary: true
  arpTimeout: 14400
  evpnRouteAdvertisementType:
    arpDynamic: true
  hostRoutePopulate:
    dynamic: false
    evpn: false
    static: false
  l3ProxyARPND:
    proxyARP: true
    proxyND: false
---
apiVersion: services.eda.nokia.com/v1alpha1
kind: IRBInterface
metadata:
  name: irb-v50
  namespace: eda
spec:
  bridgeDomain: macvrf-v50
  router: vrf2
  ipMTU: 1500
  ipAddresses:
    - ipv4Address:
        ipPrefix: 172.16.50.254/24
        primary: true
  arpTimeout: 14400
  evpnRouteAdvertisementType:
    arpDynamic: true
  hostRoutePopulate:
    dynamic: false
    evpn: false
    static: false
  l3ProxyARPND:
    proxyARP: true
    proxyND: false
---
apiVersion: services.eda.nokia.com/v1alpha1
kind: IRBInterface
metadata:
  name: irb-v60
  namespace: eda
spec:
  bridgeDomain: macvrf-v60
  router: vrf2
  ipMTU: 1500
  ipAddresses:
    - ipv4Address:
        ipPrefix: 172.16.60.254/24
        primary: true
  arpTimeout: 14400
  evpnRouteAdvertisementType:
    arpDynamic: true
  hostRoutePopulate:
    dynamic: false
    evpn: false
    static: false
  l3ProxyARPND:
    proxyARP: true
    proxyND: false
---
# VRFs
apiVersion: services.eda.nokia.com/v1alpha1
kind: Router
metadata:
  name: vrf1
  namespace: eda
spec:
  type: EVPNVXLAN
  vni: 10500
  evi: 500
  tunnelIndexPool: tunnel-index-pool
  nodeSelector:
    - eda.nokia.com/role=leaf
---
apiVersion: services.eda.nokia.com/v1alpha1
kind: Router
metadata:
  name: vrf2
  namespace: eda
spec:
  type: EVPNVXLAN
  vni: 10501
  evi: 501
  tunnelIndexPool: tunnel-index-pool
  nodeSelector:
    - eda.nokia.com/role=leaf
---
# VLANs
apiVersion: services.eda.nokia.com/v1alpha1
kind: VLAN
metadata:
  name: untagged-v10
  namespace: eda
spec:
  bridgeDomain: macvrf-v10
  interfaceSelector:
    - eda.nokia.com/untagged-v10=enabled
  vlanID: untagged
---
apiVersion: services.eda.nokia.com/v1alpha1
kind: VLAN
metadata:
  name: tagged-v10
  namespace: eda
spec:
  bridgeDomain: macvrf-v10
  interfaceSelector:
    - eda.nokia.com/tagged-v10=enabled
  vlanID: "10"
---
apiVersion: services.eda.nokia.com/v1alpha1
kind: VLAN
metadata:
  name: untagged-v20
  namespace: eda
spec:
  bridgeDomain: macvrf-v20
  interfaceSelector:
    - eda.nokia.com/untagged-v20=enabled
  vlanID: untagged
---
apiVersion: services.eda.nokia.com/v1alpha1
kind: VLAN
metadata:
  name: untagged-v30
  namespace: eda
spec:
  bridgeDomain: macvrf-v30
  interfaceSelector:
    - eda.nokia.com/untagged-v30=enabled
  vlanID: untagged
---
apiVersion: services.eda.nokia.com/v1alpha1
kind: VLAN
metadata:
  name: untagged-v40
  namespace: eda
spec:
  bridgeDomain: macvrf-v40
  interfaceSelector:
    - eda.nokia.com/untagged-v40=enabled
  vlanID: untagged
---
apiVersion: services.eda.nokia.com/v1alpha1
kind: VLAN
metadata:
  name: untagged-v50
  namespace: eda
spec:
  bridgeDomain: macvrf-v50
  interfaceSelector:
    - eda.nokia.com/untagged-v50=enabled
  vlanID: untagged
---
apiVersion: services.eda.nokia.com/v1alpha1
kind: VLAN
metadata:
  name: untagged-v60
  namespace: eda
spec:
  bridgeDomain: macvrf-v60
  interfaceSelector:
    - eda.nokia.com/untagged-v60=enabled
  vlanID: untagged
