node:
  hostname: leaf5
  role: leaf
  router_id: 192.0.2.15
  asn: 65415
underlay_interfaces:
- name: ethernet-1/31
  peer_asn: 65500
- name: ethernet-1/32
  peer_asn: 65500
lags:
- name: lag1
  description: leaf4-leaf5-lag1
  aggregate_id: '1'
  mode: all-active
  min_links: 1
  lacp:
    interval: fast
    system_id_mac: 00:00:00:00:44:55
    system_priority: 32768
    admin_key: 1
  fallback:
    mode: static
    timeout: 60
  reload_delay_timer: 100
  labels:
    untagged-v30: true
  members:
  - interface: ethernet-1/4
- name: lag2
  description: leaf2-leaf3-leaf4-leaf5-lag2
  aggregate_id: '2'
  mode: all-active
  min_links: 1
  lacp:
    interval: fast
    system_id_mac: 00:00:22:33:44:55
    system_priority: 32768
    admin_key: 2
  fallback:
    mode: static
    timeout: 60
  reload_delay_timer: 100
  labels:
    untagged-v50: true
  members:
  - interface: ethernet-1/6
- name: lag3
  description: leaf5-leaf6-lag3
  aggregate_id: '3'
  mode: port-active
  min_links: 1
  lacp:
    interval: fast
    system_id_mac: 00:00:00:00:55:66
    system_priority: 32768
    admin_key: 3
  fallback:
    mode: static
    timeout: 60
  reload_delay_timer: 100
  revertive: true
  df_preference: 800
  labels:
    untagged-v30: true
  members:
  - interface: ethernet-1/5
bridge_domains:
- name: macvrf-v10
  vni: 100101
  evi: 10
  irb:
    anycast_gw: true
    ipv4: 172.16.10.254/24
    arp_timeout: 280
    proxy_arp: true
    ip_mtu: 9198
  router: vrf1
- name: macvrf-v20
  vni: 10020
  evi: 20
  irb:
    anycast_gw: true
    ipv4: 172.16.20.254/24
    arp_timeout: 280
    proxy_arp: true
    ip_mtu: 9198
  router: vrf1
- name: macvrf-v30
  vni: 10030
  evi: 30
  access:
  - interface: lag1
    vlan: untagged
  - interface: lag3
    vlan: untagged
  irb:
    anycast_gw: true
    ipv4: 172.16.30.254/24
    arp_timeout: 280
    proxy_arp: true
    ip_mtu: 9198
  router: vrf1
- name: macvrf-v40
  vni: 10040
  evi: 40
  irb:
    anycast_gw: true
    ipv4: 172.16.40.254/24
    arp_timeout: 280
    proxy_arp: true
    ip_mtu: 9198
  router: vrf2
- name: macvrf-v50
  vni: 10050
  evi: 50
  access:
  - interface: lag2
    vlan: untagged
  irb:
    anycast_gw: true
    ipv4: 172.16.50.254/24
    arp_timeout: 280
    proxy_arp: true
    ip_mtu: 9198
  router: vrf2
- name: macvrf-v60
  vni: 10060
  evi: 60
  irb:
    anycast_gw: true
    ipv4: 172.16.60.254/24
    arp_timeout: 280
    proxy_arp: true
    ip_mtu: 9198
  router: vrf2
routers:
- name: vrf1
  vni: 10500
  evi: 500
- name: vrf2
  vni: 10501
  evi: 501
event_handler:
  node_isolation:
    down_links:
    - ethernet-1/4
    - ethernet-1/5
    - ethernet-1/6
    hold_down_time: 20000
    required_bgp_sessions: 1
