node:
  hostname: spine2
  role: spine
  router_id: 192.0.2.102
  asn: 65500
underlay_interfaces:
- name: ethernet-1/1
  peer_asn: 65411
- name: ethernet-1/2
  peer_asn: 65412
- name: ethernet-1/3
  peer_asn: 65413
- name: ethernet-1/4
  peer_asn: 65414
- name: ethernet-1/5
  peer_asn: 65415
- name: ethernet-1/6
  peer_asn: 65416
- name: ethernet-1/7
  peer_asn: 65417
- name: ethernet-1/8
  peer_asn: 65418
