{
 "title": "DC Overview",
 "time": { "from": "now-15m", "to": "now" },
 "panels": [
  {
   "title": "DC Overall Traffic",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 16, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "decbits" } },
   "targets": [
    {
     "expr": "sum(node_srl_interface_traffic_rate_in_bps)",
     "legendFormat": "{{node_name}}-{{interface_name}}:In"
    },
    {
     "expr": "sum(node_srl_interface_traffic_rate_out_bps)",
     "legendFormat": "{{node_name}}-{{interface_name}}:Out"
    }
   ]
  },
  {
   "title": "DC Overall Traffic",
   "type": "piechart",
   "gridPos": { "h": 7, "w": 4, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "decbits" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_srl_interface_traffic_rate_in_bps",
     "legendFormat": "{{node_name}}-{{interface_name}}:In"
    },
    {
     "expr": "node_srl_interface_traffic_rate_out_bps",
     "legendFormat": "{{node_name}}-{{interface_name}}:Out"
    }
   ]
  },
  {
   "title": "Throughput",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 20, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "decbits" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(node_srl_interface_traffic_rate_in_bps)",
     "legendFormat": "In"
    },
    {
     "expr": "sum(node_srl_interface_traffic_rate_out_bps)",
     "legendFormat": "Out"
    }
   ]
  },
  {
   "title": "Top Talkers Ingress",
   "type": "bargauge",
   "gridPos": { "h": 10, "w": 5, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "decbits" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sort_desc(topk(5, sum without (job, instance, namespace_name)(node_srl_interface_traffic_rate_in_bps)))",
     "legendFormat": "{{node_name}}-{{interface_name}}:In"
    }
   ]
  },
  {
   "title": "Top Talkers Egress",
   "type": "bargauge",
   "gridPos": { "h": 10, "w": 5, "x": 5, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "decbits" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sort_desc(topk(5, sum without (job, instance, namespace_name)(node_srl_interface_traffic_rate_out_bps)))",
     "legendFormat": "{{node_name}}-{{interface_name}}:In"
    }
   ]
  },
  {
   "title": "DC Overall Traffic",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 14, "x": 10, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "decbits" } },
   "targets": [
    {
     "expr": "node_srl_interface_traffic_rate_in_bps",
     "legendFormat": "{{node_name}}-{{interface_name}}:In"
    },
    {
     "expr": "node_srl_interface_traffic_rate_out_bps",
     "legendFormat": "{{node_name}}-{{interface_name}}:Out"
    }
   ]
  }
 ]
}