{
 "title": "DC Switches",
 "time": { "from": "now-15m", "to": "now" },
 "templating": {
  "list": [
   { "name": "node", "label": "Node", "query": { "query": "label_values(node_name)" } },
   {
    "name": "interface",
    "label": "Interface",
    "query": {
     "query": "label_values(node_srl_interface_traffic_rate_in_bps{node_name=\"$node\"},interface_name)"
    }
   },
   { "name": "queue", "label": "Queue", "query": { "query": "label_values(queue_queue_name)" } }
  ]
 },
 "panels": [
  {
   "title": "Node Current Throughput",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 18, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "decbits" } },
   "targets": [
    {
     "expr": "sum(node_srl_interface_traffic_rate_in_bps{node_name=\"$node\"})",
     "legendFormat": "In"
    },
    {
     "expr": "sum(node_srl_interface_traffic_rate_out_bps{node_name=\"$node\"})",
     "legendFormat": "Out"
    }
   ]
  },
  {
   "title": "Node Current Throughput",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 18, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "decbits" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(node_srl_interface_traffic_rate_in_bps{node_name=\"$node\"})",
     "legendFormat": "In"
    },
    {
     "expr": "sum(node_srl_interface_traffic_rate_out_bps{node_name=\"$node\"})",
     "legendFormat": "Out"
    }
   ]
  },
  {
   "title": "Logs Count",
   "type": "piechart",
   "gridPos": { "h": 6, "w": 3, "x": 21, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "direction": "backward",
     "expr": "sum(rate({job=\"syslog\", level=\"critical\"} |= `` [$__auto]))",
     "legendFormat": "Critical"
    },
    {
     "direction": "backward",
     "expr": "sum(rate({job=\"syslog\", level=\"warning\"} |= `` [$__auto]))",
     "legendFormat": "Warning"
    },
    {
     "direction": "backward",
     "expr": "sum(rate({job=\"syslog\", level=\"notice\"} |= `` [$__auto]))",
     "legendFormat": "Notice"
    }
   ]
  },
  {
   "title": "CPU Utilization",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 13, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "node_srl_platform_control_cpu_total_instant{node_name=\"$node\", cpu_index!~\"2|all\"}",
     "legendFormat": "{{cpu_index}}"
    }
   ]
  },
  {
   "title": "Overall CPU Utilization",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 13, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_srl_platform_control_cpu_total_instant{node_name=\"$node\", cpu_index=\"all\"}",
     "legendFormat": "{{cpu_index}}"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "decbits" } },
   "targets": [
    {
     "expr": "node_srl_platform_control_memory_free{node_name=\"$node\"}",
     "legendFormat": "Free"
    },
    {
     "expr": "node_srl_platform_control_memory_utilization{node_name=\"$node\"}",
     "legendFormat": "Utilization"
    },
    {
     "expr": "node_srl_platform_control_memory_reserved{node_name=\"$node\"}",
     "legendFormat": "Reserved"
    },
    {
     "expr": "node_srl_platform_control_memory_physical{node_name=\"$node\"}",
     "legendFormat": "Physical"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 13, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "decbits" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_srl_platform_control_memory_free{node_name=\"$node\"}",
     "legendFormat": "Free"
    },
    {
     "expr": "node_srl_platform_control_memory_utilization{node_name=\"$node\"}",
     "legendFormat": "Utilization"
    },
    {
     "expr": "node_srl_platform_control_memory_reserved{node_name=\"$node\"}",
     "legendFormat": "Reserved"
    },
    {
     "expr": "node_srl_platform_control_memory_physical{node_name=\"$node\"}",
     "legendFormat": "Physical"
    }
   ]
  },
  {
   "title": "$node All Interface Throughput",
   "type": "timeseries",
   "gridPos": { "h": 15, "w": 15, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "decbits" } },
   "targets": [
    {
     "expr": "node_srl_interface_traffic_rate_in_bps{node_name=\"$node\"}",
     "legendFormat": "{{interface_name}}:In"
    },
    {
     "expr": "node_srl_interface_traffic_rate_out_bps{node_name=\"$node\"}",
     "legendFormat": "{{interface_name}}:Out"
    }
   ]
  },
  {
   "title": "In Discarded Packets - SubInterface",
   "type": "bargauge",
   "gridPos": { "h": 5, "w": 9, "x": 15, "y": 14 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_srl_interface_subinterface_statistics_in_discarded_packets{node_name=\"$node\",interface_name!=\"mgmt0\"}",
     "legendFormat": "In-{{interface_name}}"
    }
   ]
  },
  {
   "title": "Out Discarded Packets - SubInterface",
   "type": "bargauge",
   "gridPos": { "h": 5, "w": 9, "x": 15, "y": 19 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_srl_interface_subinterface_statistics_out_discarded_packets{node_name=\"$node\",interface_name!=\"mgmt0\"}",
     "legendFormat": "In-{{interface_name}}"
    }
   ]
  },
  {
   "title": "Discarded Packets Subinterfaces",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 9, "x": 15, "y": 24 },
   "targets": [
    {
     "expr": "node_srl_interface_subinterface_statistics_in_discarded_packets{node_name=\"$node\",interface_name!=\"mgmt0\"}",
     "legendFormat": "In-{{interface_name}}"
    },
    {
     "expr": "node_srl_interface_subinterface_statistics_out_discarded_packets{node_name=\"$node\",interface_name!=\"mgmt0\"}",
     "legendFormat": "Out-{{interface_name}}"
    }
   ]
  },
  {
   "title": "$node - $interface",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "decbits" } },
   "targets": [
    {
     "expr": "node_srl_interface_traffic_rate_in_bps{node_name=\"$node\", interface_name=\"$interface\"}",
     "legendFormat": "{{interface_name}}:In"
    },
    {
     "expr": "node_srl_interface_traffic_rate_out_bps{node_name=\"$node\", interface_name=\"$interface\"}",
     "legendFormat": "{{interface_name}}:Out"
    }
   ]
  },
  {
   "title": "Select Interfaces",
   "type": "volkovlabs-variable-panel",
   "gridPos": { "h": 12, "w": 3, "x": 0, "y": 39 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Select Queue",
   "type": "volkovlabs-variable-panel",
   "gridPos": { "h": 12, "w": 2, "x": 3, "y": 39 },
   "targets": [
    {}
   ]
  },
  {
   "title": "$queue Egress Transmitted",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 9, "x": 5, "y": 39 },
   "targets": [
    {
     "expr": "node_srl_qos_interfaces_interface_output_queues_queue_queue_statistics_aggregate_statistics_transmitted_packets{node_name=\"$node\", interface_interface_id=\"$interface\", queue_queue_name=\"$queue\"}",
     "legendFormat": "{{interface_interface_id}}-{{queue_queue_name}}"
    }
   ]
  },
  {
   "title": "$queue Egress Dropped",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 10, "x": 14, "y": 39 },
   "targets": [
    {
     "expr": "node_srl_qos_interfaces_interface_output_queues_queue_queue_statistics_aggregate_statistics_dropped_packets{node_name=\"$node\", interface_interface_id=\"$interface\", queue_queue_name=\"$queue\"}",
     "legendFormat": "{{interface_interface_id}}-{{queue_queue_name}}"
    }
   ]
  },
  {
   "title": "$node PFC Pause Generated",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 7, "x": 0, "y": 51 },
   "targets": [
    {
     "expr": "node_srl_qos_interfaces_interface_pfc_statistics_total_pfc_pause_frames_generated{node_name=\"$node\"}",
     "legendFormat": "{{interface_interface_id}}"
    }
   ]
  },
  {
   "title": "$node PFC Pause Generated",
   "type": "bargauge",
   "gridPos": { "h": 9, "w": 6, "x": 7, "y": 51 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_srl_qos_interfaces_interface_pfc_statistics_total_pfc_pause_frames_generated{node_name=\"$node\"}",
     "legendFormat": "{{interface_interface_id}}"
    }
   ]
  },
  {
   "title": "$node PFC Pause Received",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 5, "x": 13, "y": 51 },
   "targets": [
    {
     "expr": "node_srl_qos_interfaces_interface_pfc_statistics_total_pfc_pause_frames_received{node_name=\"$node\"}",
     "legendFormat": "{{interface_interface_id}}"
    }
   ]
  },
  {
   "title": "$node - PFC Pause Received",
   "type": "bargauge",
   "gridPos": { "h": 9, "w": 6, "x": 18, "y": 51 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_srl_qos_interfaces_interface_pfc_statistics_total_pfc_pause_frames_generated{node_name=\"$node\"}",
     "legendFormat": "{{interface_interface_id}}"
    }
   ]
  },
  {
   "title": "Logs $node",
   "type": "logs",
   "gridPos": { "h": 15, "w": 15, "x": 0, "y": 60 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{job=\"syslog\"} |= ``"
    }
   ]
  },
  {
   "title": "Interface Status",
   "type": "state-timeline",
   "gridPos": { "h": 10, "w": 9, "x": 15, "y": 60 },
   "targets": [
    {
     "expr": "node_srl_interface_oper_state{node_name=\"$node\"}\n  * on(interface_name, node_name)\n    (node_srl_interface_admin_state{node_name=\"$node\"} == 1)",
     "legendFormat": "{{interface_name}}"
    }
   ]
  },
  {
   "title": "Network Instance",
   "type": "state-timeline",
   "gridPos": { "h": 5, "w": 9, "x": 15, "y": 70 },
   "targets": [
    {
     "expr": "node_srl_network_instance_oper_state{node_name=\"$node\"}",
     "legendFormat": "{{network_instance_name}}"
    }
   ]
  }
 ]
}