# © 2025 Nokia  
# Licensed under the BSD 3-Clause License  
# SPDX-License-Identifier: BSD-3-Clause  

apiVersion: config.eda.nokia.com/v1alpha1
kind: Configlet
metadata:
  name: bgp-evpn-rapid
  namespace: eda
spec:
  endpointSelector:
    - eda.nokia.com/role=leaf
    - eda.nokia.com/role=spine
  operatingSystem: srl
  priority: 100
  configs:
    - path: .network-instance{.name=="default"}.protocols.bgp.afi-safi{.afi-safi-name=="evpn"}.evpn
      operation: Update
      config: |-
        {
          "rapid-update": "true"
        }
---
apiVersion: config.eda.nokia.com/v1alpha1
kind: Configlet
metadata:
  name: bgp-rapid-route-withdraw
  namespace: eda
spec:
  endpointSelector:
    - eda.nokia.com/role=leaf
    - eda.nokia.com/role=spine
  operatingSystem: srl
  priority: 100
  configs:
    - path: .network-instance{.name=="default"}.protocols.bgp.route-advertisement
      operation: Update
      config: |-
        {
          "rapid-withdrawal": "true"
        }