# © 2025 Nokia  
# Licensed under the BSD 3-Clause License  
# SPDX-License-Identifier: BSD-3-Clause  

# nodeprofile for v24.10.2
apiVersion: core.eda.nokia.com/v1
kind: NodeProfile
metadata:
  name: clab-srlinux-24.10.2
  namespace: eda
spec:
  images:
    - image: srlimages/srlinux-24.10.2-bin/srlinux.bin
      imageMd5: srlimages/srlinux-24.10.2-md5/srlinux.md5
  nodeUser: admin
  operatingSystem: srl
  port: 57410
  version: 24.10.2
  versionMatch: v24\.10\.2.*
  versionPath: .system.information.version
  yang: https://eda-asvr.eda-system/eda-system/schemaprofiles/srlinux-ghcr-24.10.2/srlinux-24.10.2.zip
  # set annotate to true for source EDA CRs to be added as a description in configuration lines
  # choosing false to prefer configuration readability
  annotate: false 