- name: Get software version
  nokia.srlinux.get:
    paths:
    - path: /platform/control[slot=A]/software-version
      datastore: state
  register: version_result
  no_log: true
- name: Set sw_version fact
  ansible.builtin.set_fact:
    sw_version: '{{ version_result.result[0].split(''-'')[0] }}'
  no_log: true
- name: Initialize config accumulators
  ansible.builtin.set_fact:
    config_update: []
    config_replace: []
    config_delete: []
  no_log: true
