node:
  hostname: leaf1
  role: leaf
  router_id: 192.168.254.11
  asn: 65411
  labels:
    eda.nokia.com/role: leaf
    eda.nokia.com/name: leaf1
    eda.nokia.com/security-profile: managed
underlay_interfaces:
- name: ethernet-1/31
  peer_asn: 65500
- name: ethernet-1/32
  peer_asn: 65500
edge_interfaces:
- name: ethernet-1/3
  encap: dot1q
  labels:
    eda.nokia.com/role: edge
    eda.nokia.com/tagged-v10: enabled
    eda.nokia.com/tagged-v99: enabled
- name: ethernet-1/5
  encap: dot1q
  labels:
    eda.nokia.com/role: edge
    eda.nokia.com/untagged-v40: enabled
irb_interfaces:
- bridge_domain: macvrf-v10
  router: vrf1
  ipv4: 172.16.10.254/24
  anycast_gw: true
  proxy_arp: true
  arp_timeout: 280
  ip_mtu: 9394
  evpn_route_advertisement_type:
    rfc9135SymmetricMode: false
    arpDynamic: true
    arpStatic: true
    ndDynamic: false
    ndStatic: false
  host_route_populate:
    dynamic: true
    static: true
    evpn: false
- bridge_domain: macvrf-v20
  router: vrf1
  ipv4: 172.16.20.254/24
  anycast_gw: true
  proxy_arp: true
  arp_timeout: 280
  ip_mtu: 9394
  evpn_route_advertisement_type:
    rfc9135SymmetricMode: false
    arpDynamic: true
    arpStatic: true
    ndDynamic: false
    ndStatic: false
  host_route_populate:
    dynamic: true
    static: true
    evpn: false
- bridge_domain: macvrf-v30
  router: vrf1
  ipv4: 172.16.30.254/24
  anycast_gw: true
  proxy_arp: true
  arp_timeout: 280
  ip_mtu: 9394
  evpn_route_advertisement_type:
    rfc9135SymmetricMode: false
    arpDynamic: true
    arpStatic: true
    ndDynamic: false
    ndStatic: false
  host_route_populate:
    dynamic: true
    static: true
    evpn: false
- bridge_domain: macvrf-v40
  router: vrf2
  ipv4: 172.16.40.254/24
  anycast_gw: true
  proxy_arp: true
  arp_timeout: 280
  ip_mtu: 9394
  evpn_route_advertisement_type:
    rfc9135SymmetricMode: false
    arpDynamic: true
    arpStatic: true
    ndDynamic: false
    ndStatic: false
  host_route_populate:
    dynamic: true
    static: true
    evpn: false
- bridge_domain: macvrf-v50
  router: vrf2
  ipv4: 172.16.50.254/24
  anycast_gw: true
  proxy_arp: true
  arp_timeout: 280
  ip_mtu: 9394
  evpn_route_advertisement_type:
    rfc9135SymmetricMode: false
    arpDynamic: true
    arpStatic: true
    ndDynamic: false
    ndStatic: false
  host_route_populate:
    dynamic: true
    static: true
    evpn: false
- bridge_domain: macvrf-v60
  router: vrf2
  ipv4: 172.16.60.254/24
  anycast_gw: true
  proxy_arp: true
  arp_timeout: 280
  ip_mtu: 9394
  evpn_route_advertisement_type:
    rfc9135SymmetricMode: false
    arpDynamic: true
    arpStatic: true
    ndDynamic: false
    ndStatic: false
  host_route_populate:
    dynamic: true
    static: true
    evpn: false
routed_interfaces:
- name: leaf-s5
  interface: ethernet-1/4
  router: vrf1
  vlan_id: 'null'
  ip_mtu: 1500
  arp_timeout: 14400
  ipv4_addresses:
  - ip_prefix: 172.16.100.0/31
    primary: true
static_routes:
- name: static-s5
  router: vrf1
  prefixes:
  - 172.16.92.0/24
  - 172.16.93.0/24
  - 172.16.94.0/24
  - 172.16.95.0/24
  nexthop_group:
    name: static-s5
    nexthops:
    - ip_address: 172.16.100.1
      resolve: false
default_mtu:
  interface_mtu: 9412
  layer2_subif_mtu: 9412
  layer3_mtu: 9394
config_overrides:
- path: /system/information
  value:
    contact: support@nokia.com
