node:
  hostname: leaf7
  role: leaf
  router_id: 192.168.254.17
  asn: 65417
  labels:
    eda.nokia.com/role: leaf
    eda.nokia.com/name: leaf7
    eda.nokia.com/security-profile: managed
underlay_interfaces:
- name: ethernet-1/31
  peer_asn: 65500
- name: ethernet-1/32
  peer_asn: 65500
irb_interfaces:
- bridge_domain: macvrf-v10
  router: vrf1
  ipv4: 172.16.10.254/24
  anycast_gw: true
  proxy_arp: true
  arp_timeout: 280
  ip_mtu: 9394
  evpn_route_advertisement_type:
    rfc9135SymmetricMode: false
    arpDynamic: true
    arpStatic: true
    ndDynamic: false
    ndStatic: false
  host_route_populate:
    dynamic: true
    static: true
    evpn: false
- bridge_domain: macvrf-v20
  router: vrf1
  ipv4: 172.16.20.254/24
  anycast_gw: true
  proxy_arp: true
  arp_timeout: 280
  ip_mtu: 9394
  evpn_route_advertisement_type:
    rfc9135SymmetricMode: false
    arpDynamic: true
    arpStatic: true
    ndDynamic: false
    ndStatic: false
  host_route_populate:
    dynamic: true
    static: true
    evpn: false
- bridge_domain: macvrf-v30
  router: vrf1
  ipv4: 172.16.30.254/24
  anycast_gw: true
  proxy_arp: true
  arp_timeout: 280
  ip_mtu: 9394
  evpn_route_advertisement_type:
    rfc9135SymmetricMode: false
    arpDynamic: true
    arpStatic: true
    ndDynamic: false
    ndStatic: false
  host_route_populate:
    dynamic: true
    static: true
    evpn: false
- bridge_domain: macvrf-v40
  router: vrf2
  ipv4: 172.16.40.254/24
  anycast_gw: true
  proxy_arp: true
  arp_timeout: 280
  ip_mtu: 9394
  evpn_route_advertisement_type:
    rfc9135SymmetricMode: false
    arpDynamic: true
    arpStatic: true
    ndDynamic: false
    ndStatic: false
  host_route_populate:
    dynamic: true
    static: true
    evpn: false
- bridge_domain: macvrf-v50
  router: vrf2
  ipv4: 172.16.50.254/24
  anycast_gw: true
  proxy_arp: true
  arp_timeout: 280
  ip_mtu: 9394
  evpn_route_advertisement_type:
    rfc9135SymmetricMode: false
    arpDynamic: true
    arpStatic: true
    ndDynamic: false
    ndStatic: false
  host_route_populate:
    dynamic: true
    static: true
    evpn: false
- bridge_domain: macvrf-v60
  router: vrf2
  ipv4: 172.16.60.254/24
  anycast_gw: true
  proxy_arp: true
  arp_timeout: 280
  ip_mtu: 9394
  evpn_route_advertisement_type:
    rfc9135SymmetricMode: false
    arpDynamic: true
    arpStatic: true
    ndDynamic: false
    ndStatic: false
  host_route_populate:
    dynamic: true
    static: true
    evpn: false
default_mtu:
  interface_mtu: 9412
  layer2_subif_mtu: 9412
  layer3_mtu: 9394
config_overrides:
- path: /system/information
  value:
    contact: support@nokia.com
