bgp:
  preference:
    ebgp: 170
    ibgp: 170
  route_advertisement:
    rapid_withdrawal: true
    wait_for_fib_install: false
  afi_safi:
    evpn:
      multipath_max_paths: 64
      inter_as_vpn: true
      rapid_update: true
    ipv4_unicast:
      multipath_max_paths: 2
      advertise_ipv6_next_hops: true
      receive_ipv6_next_hops: true
      rapid_update: true
    ipv6_unicast:
      multipath_max_paths: 2
      rapid_update: true
  group_name: bgpgroup-ebgp-dc1
  ebgp_default_policy:
    import_reject_all: true
    export_reject_all: true
bfd:
  desired_min_transmit_interval: 1000000
  required_min_receive: 1000000
  detection_multiplier: 3
  min_echo_receive_interval: 1000000
routing_policy:
  prefix_set: prefixset-dc1
  export_policy: ebgp-isl-export-policy-dc1
  import_policy: ebgp-isl-import-policy-dc1
  prefix_sets:
  - name: prefixset-dc1
    prefixes:
    - ip_prefix: 192.168.254.0/24
      mask_length_range: 32..32
  policies:
  - name: ebgp-isl-export-policy-dc1
    default_action: reject
    statements:
    - name: '10'
      match:
        prefix_set: prefixset-dc1
        protocol: local
      action:
        result: accept
        set_local_preference: 100
    - name: '15'
      match:
        protocol: bgp
      action:
        result: accept
        set_local_preference: 100
    - name: '20'
      match:
        protocol: aggregate
      action:
        result: accept
        set_local_preference: 100
    - name: '25'
      match:
        bgp_evpn_route_types:
        - 1
      action:
        result: accept
        set_local_preference: 100
    - name: '30'
      match:
        bgp_evpn_route_types:
        - 2
      action:
        result: accept
        set_local_preference: 100
    - name: '35'
      match:
        bgp_evpn_route_types:
        - 3
      action:
        result: accept
        set_local_preference: 100
    - name: '40'
      match:
        bgp_evpn_route_types:
        - 4
      action:
        result: accept
        set_local_preference: 100
    - name: '45'
      match:
        bgp_evpn_route_types:
        - 5
      action:
        result: accept
        set_local_preference: 100
  - name: ebgp-isl-import-policy-dc1
    default_action: reject
    statements:
    - name: '10'
      match:
        protocol: bgp
      action:
        result: accept
        set_local_preference: 100
    - name: '25'
      match:
        bgp_evpn_route_types:
        - 1
      action:
        result: accept
        set_local_preference: 100
    - name: '30'
      match:
        bgp_evpn_route_types:
        - 2
      action:
        result: accept
        set_local_preference: 100
    - name: '35'
      match:
        bgp_evpn_route_types:
        - 3
      action:
        result: accept
        set_local_preference: 100
    - name: '40'
      match:
        bgp_evpn_route_types:
        - 4
      action:
        result: accept
        set_local_preference: 100
    - name: '45'
      match:
        bgp_evpn_route_types:
        - 5
      action:
        result: accept
        set_local_preference: 100
bridge_domains:
- name: macvrf-v10
  vni: 100101
  evi: 10
  mac_duplication:
    enabled: true
    hold_down_time: 9
    monitoring_window: 3
    action: StopLearning
    num_moves: 5
- name: macvrf-v20
  vni: 10020
  evi: 20
  mac_duplication:
    enabled: true
    hold_down_time: 9
    monitoring_window: 3
    action: StopLearning
    num_moves: 5
- name: macvrf-v30
  vni: 10030
  evi: 30
  mac_duplication:
    enabled: true
    hold_down_time: 9
    monitoring_window: 3
    action: StopLearning
    num_moves: 5
- name: macvrf-v40
  vni: 10040
  evi: 40
  mac_duplication:
    enabled: true
    hold_down_time: 9
    monitoring_window: 3
    action: StopLearning
    num_moves: 5
- name: macvrf-v50
  vni: 10050
  evi: 50
  mac_duplication:
    enabled: true
    hold_down_time: 9
    monitoring_window: 3
    action: StopLearning
    num_moves: 5
- name: macvrf-v60
  vni: 10060
  evi: 60
  mac_duplication:
    enabled: true
    hold_down_time: 9
    monitoring_window: 3
    action: StopLearning
    num_moves: 5
routers:
- name: vrf1
  vni: 10500
  evi: 500
  node_selector:
  - eda.nokia.com/role=leaf
- name: vrf2
  vni: 10501
  evi: 501
  node_selector:
  - eda.nokia.com/role=leaf
vlans:
- name: tagged-v10
  bridge_domain: macvrf-v10
  vlan_id: '10'
  interface_selector:
  - eda.nokia.com/tagged-v10=enabled
- name: untagged-v10
  bridge_domain: macvrf-v10
  vlan_id: untagged
  interface_selector:
  - eda.nokia.com/untagged-v10=enabled
- name: untagged-v20
  bridge_domain: macvrf-v20
  vlan_id: untagged
  interface_selector:
  - eda.nokia.com/untagged-v20=enabled
- name: untagged-v30
  bridge_domain: macvrf-v30
  vlan_id: untagged
  interface_selector:
  - eda.nokia.com/untagged-v30=enabled
- name: untagged-v40
  bridge_domain: macvrf-v40
  vlan_id: untagged
  interface_selector:
  - eda.nokia.com/untagged-v40=enabled
- name: untagged-v50
  bridge_domain: macvrf-v50
  vlan_id: untagged
  interface_selector:
  - eda.nokia.com/untagged-v50=enabled
- name: untagged-v60
  bridge_domain: macvrf-v60
  vlan_id: untagged
  interface_selector:
  - eda.nokia.com/untagged-v60=enabled
