bgp:
  preference:
    ebgp: 170
    ibgp: 170
  route_advertisement:
    rapid_withdrawal: true
    wait_for_fib_install: false
  afi_safi:
    evpn:
      multipath_max_paths: 64
      inter_as_vpn: true
      rapid_update: true
    ipv4_unicast:
      multipath_max_paths: 6
      advertise_ipv6_next_hops: true
      receive_ipv6_next_hops: true
      rapid_update: true
    ipv6_unicast:
      multipath_max_paths: 6
      rapid_update: true
  group_name: bgpgroup-ebgp-dc1
  ebgp_default_policy:
    import_reject_all: true
    export_reject_all: true
bfd:
  desired_min_transmit_interval: 1000000
  required_min_receive: 1000000
  detection_multiplier: 3
  min_echo_receive_interval: 1000000
routing_policy:
  prefix_set: prefixset-dc1
  export_policy: ebgp-isl-export-policy-dc1
  import_policy: ebgp-isl-import-policy-dc1
  prefix_sets:
  - name: prefixset-dc1
    prefixes:
    - ip_prefix: 192.168.254.0/24
      mask_length_range: 32..32
  policies:
  - name: ebgp-isl-export-policy-dc1
    default_action: reject
    statements:
    - name: '10'
      match:
        prefix_set: prefixset-dc1
        protocol: local
      action:
        result: accept
        set_local_preference: 100
    - name: '15'
      match:
        protocol: bgp
      action:
        result: accept
        set_local_preference: 100
    - name: '20'
      match:
        protocol: aggregate
      action:
        result: accept
        set_local_preference: 100
    - name: '25'
      match:
        bgp_evpn_route_types:
        - 1
      action:
        result: accept
        set_local_preference: 100
    - name: '30'
      match:
        bgp_evpn_route_types:
        - 2
      action:
        result: accept
        set_local_preference: 100
    - name: '35'
      match:
        bgp_evpn_route_types:
        - 3
      action:
        result: accept
        set_local_preference: 100
    - name: '40'
      match:
        bgp_evpn_route_types:
        - 4
      action:
        result: accept
        set_local_preference: 100
    - name: '45'
      match:
        bgp_evpn_route_types:
        - 5
      action:
        result: accept
        set_local_preference: 100
  - name: ebgp-isl-import-policy-dc1
    default_action: reject
    statements:
    - name: '10'
      match:
        protocol: bgp
      action:
        result: accept
        set_local_preference: 100
    - name: '25'
      match:
        bgp_evpn_route_types:
        - 1
      action:
        result: accept
        set_local_preference: 100
    - name: '30'
      match:
        bgp_evpn_route_types:
        - 2
      action:
        result: accept
        set_local_preference: 100
    - name: '35'
      match:
        bgp_evpn_route_types:
        - 3
      action:
        result: accept
        set_local_preference: 100
    - name: '40'
      match:
        bgp_evpn_route_types:
        - 4
      action:
        result: accept
        set_local_preference: 100
    - name: '45'
      match:
        bgp_evpn_route_types:
        - 5
      action:
        result: accept
        set_local_preference: 100
