- name: Configure dc1 fabric
  hosts: all
  gather_facts: false
  roles:
  - role: detect
    tags:
    - always
  - role: topology
    tags:
    - topology
  - role: fabric
    tags:
    - fabric
  - role: services
    tags:
    - services
  - role: purge
    tags:
    - never
    - full
    when: purge | default(true) | bool
  - role: configure
    tags:
    - always
- name: Confirm dc1 fabric changes
  hosts: all
  gather_facts: false
  any_errors_fatal: true
  roles:
  - role: confirm
