# fabric deployment for collapsed spine design
apiVersion: fabrics.eda.nokia.com/v1alpha1
kind: Fabric
metadata:
  name: dc1-collapsed-spine
  namespace: 2-spine-collapsed
spec:
  systemPoolIPV4: system0
  leafs:
    leafNodeSelector:
      - eda.nokia.com/role=collapsed-spine
    asnPool: collapsed-spine-asn
  interSwitchLinks:
    unnumbered: IPV6
    linkSelector:
      - eda.nokia.com/role=interSwitch
  underlayProtocol:
    protocol:
      - EBGP
    bfd:
      enabled: true
      detectionMultiplier: 3
      minEchoReceiveInterval: 250000
      desiredMinTransmitInt: 250000
      requiredMinReceive: 250000
    bgp:
      asnPool: collapsed-spine-asn
  overlayProtocol:
    protocol: EBGP
