node:
  hostname: spine1
  role: spine
  router_id: 10.0.0.101
  asn: 65500
underlay_interfaces:
- name: ethernet-1/1
  peer_asn: 65001
- name: ethernet-1/2
  peer_asn: 65002
- name: ethernet-1/3
  peer_asn: 65003
- name: ethernet-1/4
  peer_asn: 65004
- name: ethernet-1/5
  peer_asn: 65005
- name: ethernet-1/6
  peer_asn: 65006
